config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :posts
  resources :comments
  
  get '/sub_category', to: "posts#sub_category"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post
	
	# def new
	# 	debugger
	# 	@comment = @post.comments.new
	# end

	def create
		@comment = @post.comments.new(comment_params)
		respond_to do |format|
			if @comment.save
				format.html {redirect_to posts_path }
				format.js
			else
				format.html { render 'new'}
				format.js
			end
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:comment,:post_id)
	end

	def set_post
		if params[:post_id]
			@post = Post.find(params[:post_id])
		else
			@post = Post.find(params[:comment][:post_id])
		end
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# @posts = Post.all

		@posts = Post.all.includes(:comments)
		
		# @comment = Comment.all.last
		# if @comment.present?
		# 	@comment = Post.find(@comment.post_id)
		# end
	end

	def new
		@post = Post.new
	end

	def create
		@posts = Post.all
		@post = Post.create(post_params)
		@post_last = Post.last
		respond_to do |format|
			if @post.save
	
				  format.html { redirect_to posts_path}#handle HTML, i.e. full page reload 
				  format.js {} # handle ajax request
			else
				format.html { render 'new'}
				format.js { }	
			end
		end	
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to @post}
				format.js {}
				# redirect_to @post
			else
				render 'edit'
			end
		end
	end

	def sub_category
		debugger
	end

	private
	def post_params
		params.require(:post).permit(:title,:body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<!-- <div><%#= comment.comment %></div> -->
<%# if @post %>
	<tr >
		<td>
			<% if @comment %>
				<%= @comment.comment %>
			<% else %>
				<%= comment.comment %>
			<% end %>
		</td>
	</tr>

<%# end %>

	
	<%# debugger %>

app/views/comments/_form.html.erb
<%# debugger %>
<%= form_with model: [@comment], remote: true, id: 'comment_form' do |form| %>
	<p>
		<%= form.label :comment %>
		<%= form.text_field :comment %>
	</p>
	<p>
		<%= form.hidden_field :post_id ,value: @post.id %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/comments/create.js.erb
<%# debugger %>
$('#comment_form').remove();
// $('#cp_<%= @post.id %>').append("<%= j render partial: 'comments/comment', :locals => { :comment => @comment }  %>");
$('#cp_<%= @post.id %>').append("<%= j render partial: 'comments/comment', :locals => { :comment => @comment, :post => @post }  %>");

// $('#cp_<%= @post.id %>').append("<%= j render partial:  @comment  %>");
$('#comment_c<%= @post.id %>').text('<% count = @post.comments.count %> <%= count > 0 ? count : " " %>');













// $('#comment_form').remove();
// $('#cp_<%= @post.id %>').append("<%= escape_javascript(render(partial: 'comment' , comment: @comment))%>")
// $('#comments').append("<%= j render partial: @comment , locals: {comment: @comment }%>")


// witout partial
// $('#comment_form').remove();
// ele = document.createElement("div");
// ele.className= "remove";
// <%# debugger %>
// ele.innerHTML = "<strong>Comment:</strong> <%= @comment.comment %>";
// $('.uploader').find(' #comment_show<%= @post.id %>').append(ele)

// $('#comment_<%= @post.id %>').text('<% count = @post.comments.count %><%= count > 0 ? count : ""  %>')









 // $("#comments").html("<%= escape_javascript(render partial: 'comments/comment', collection: @post.comments, as: :comment) %>");



























// $("#comments").prepend("<%= j render partial: 'comment',locals: {comment: @comment} %>");

// $("#comments").prepend("<%= j render partial: 'comment' %>")

app/views/comments/new.html.erb
<%= render 'comments/form' %>

app/views/comments/new.js.erb
// show = document.getElementById('show<%= @post.id %>');
// hide = document.getElementById('hide<%= @post.id %>');

// if (show.innerText == "comment" && show.value == "comment"){

// 	show.value = "hide";
// 	show.style.display = "none";
// 	$('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");	 	 
// 	document.getElementById('hide<%= @post.id %>').style = "block";
// }
// else{

// 	show.value = "comment";
// 	$('#comment-<%= @post.id %>').hide();
// 	$('#cp_<%= @post.id %>').hide();
// 	hide.style.display = "none";

// 	document.getElementById('show<%= @post.id %>').style= "block";	
// }
















// if (hide.innerText == "hide"){
// 	debugger
// }

// document.getElementById('show<%= @post.id %>').onclick = myFunction;
// function myFunction(){
// 	alert("hello");
// }
// button = document.getElementById('show<%= @post.id %>');
// $('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");	 	 

// if (button.innerText == 'comment'){
// 	button.style.display = "none";
// 	// debugger
// 	 document.getElementById('hide<%= @post.id %>').style = "block";

// }
// else{
// 	debugger
// 	 $('#comment-<%= @post.id %>').hide();
// }


// document.getElementById('show<%= @post.id %>').addEventListener("click", function() {
//   alert("Hello World!");
// });

// document.getElementById('show<%= @post.id %>').addEventListener("click", myFunction);

// function myFunction() {
// 	debugger
//   document.getElementById("demo").innerHTML = Date();
// }



// var button = document.querySelector('#c<%= @post.id %>');


	
// $('#c<%= @post.id %>').click(function(){
	
// 	if (button.innerText == 'comment')
// 	{

// 		$('#c<%= @post.id %>[href]')
// 		// button.firstChild.text = "hide"
// 		document.getElementById('c<%= @post.id %>').innerText = "hide"
// 		debugger
// 		button.innerText = "hide";
// 		// $('#comment-<%= @post.id %>').show();
// 		$('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");	 	 
// 		// $('.table2').show();
// 	}
// 	else 
// 	{
// 		// button.firstChild.text = "comment"
// 		document.getElementById('#c<%= @post.id %>').innerText = "comment";	
// 		$('#comment-<%= @post.id %>').hide();
// 		$('.table2').hide();
		
// 	}
// });


































































































// document.getElementById('comment').onclick = function() {change()}
// function change(){
// 	document.querySelector('#comment').value = 'Hide';
// 		// $('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");
// 		// $('#comment-<%= @post.id %>').click(function(){
// 		// 	debugger
// 		// })
// }
// "comment_link#{post.id}"
// debugger
// $('comment_link#{@post.id}').click(function(e){
// debugger
// 	// e.preventDefault();
// 	$("#comment_form").show();

// });
// $(document).ready(function(){



//  const button = document.getElementById('comment_link<%= @post.id %>');
// 	button.addEventListener('click',function(e){
// 		e.preventDefault();
// 		$('.table2').hide();
// 		if(button.innerText == "comment"){

// 			$('#cp_<%= @post.id %>').show();
// 			button.innerText = "Hide";
// 			$('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");
// 		}
// 		else if(button.innerText.toLowerCase() == 'hide') {
// 			button.innerText = "Comment";
// 			$('#cp_<%= @post.id %>').hide();
// 		}
// 		else {
// 			button.innerText = "comment";
// 			$('#comment_form').hide();
// 			$('.table1').show();
// 		}
		
// 	});
// });


// $(function(){
//  const button = document.getElementById('comment_link<%= @post.id %>');

// 	button.addEventListener('click',function(){

// 		if(button.innerText == "comment"){
		
// 			button.innerText = "hide";
// 			$('.table2').show();
// 			$('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");
// 		}
// 		else
// 		{
// 			button.innerText = "comment";
// 			$('.table2').hide(); 
// 			$('.c td').hide();
// 			$('#comment-<%= @post.id %>').hide();
// 		}
// 		// else if(button.innerText == 'hide') {
// 		// 	button.innerText = "Comment";
// 		// 	$('.table2').hide();
// 		// }
// 		// else {
// 		// 	$('.table1').show();
// 		// 	button.innerText = "comment";
// 		// 	$('#comment_form').hide();
// 		// }
		
// 	});
// });





















// let button = document.getElementById('comment_link');

// button.addEventListener('click', function() {
//   if(button.innerText.toLowerCase() == 'comment') {

//     button.innerText = 'Hide';
//     	debugger
//   }
//   else {
//     button.innerText = 'Comment';
//   }
// });
// $(document).ready(function() {
//     $("#comment_link").click(function(){
//     	// $('.table2').hide();
//     	$('.table2').slideToggle("fast");

//     	$('#comment.link')
//         debugger
//     }); 
// });


// $(document).ready(function() {
//     $("#comment_link").click(function(){
//     	// $('.table2').hide();
//     	$('.table2').slideToggle("fast");

//     	$('#comment.link')
//         debugger
//     }); 
// });



// $('#comment-<%= @post.id %>').html("<%= j render :partial => 'comments/form', :locals => { :comment => @comment } %>");
// $('#comment_link').html("hide");
// $('.comment').html("<%= j render partial: 'comments/form' %>")
 

//  $("button.btn-tag-cat").click(function(e) {
//   e.preventDefault();
//   var id = $(this).attr('id');
//   alert(id);
//   $('#' + id).find('span').show();
// });
// <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

// <button class="btn-tag-cat" id="hallo">Press</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: [@post],remote: true ,id: 'form' do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :body %>
		<%= form.text_area :body %>
	</p>

	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/posts/_post.html.erb
	
<tr>
	<td><%= post.title %></td>

	<td><%= post.body %></td>
		<!-- <td class></td> -->
	
	<td class="c">
		
		  <button id= "show<%= post.id %>" class = "hello" value = "comment"><%= link_to 'comment', comments_path(post_id: post.id),remote: true,method: :post, id: "co", class: "com"%></button>
		 <button id= "hide<%= post.id %>" value = "hide" style = "display: none;"><%= link_to 'hide', new_comment_path(post_id: post.id),remote: true, id: "co", class: "com"%></button>
		
		<%#= button_to 'comment', new_comment_path(post_id: post.id), remote: true, class: post.id %>
		
			<table id="cp_<%= post.id %>" class="table2"> 
				<tr>
					<th>Comment</th>
				</tr> 
				<div class="collection">
					<div class="comment" id="comment-<%= post.id %>">
						
					</div>
					<% post.comments.each do |comment| %>
						<%= render :partial => "comments/comment", :locals => { :comment => comment , :post => post.id} %>
					<% end %>	</div>	
			</table> 
		</td>

		<td>
			<div id="comment_c<%= post.id %>">
						<% count = post.comments.count %>
						<%= count > 0 ? count : " " %>	
					</div>	
		</td>
		<!-- <td><div class="comment" id="comment-<%= post.id %>"></div></td> -->
</tr>
			
		<!-- <tr><td id="posts"></td></tr> -->
			
<script>
	$(document).ready(function(){
		$('#show<%= post.id %>').on("click", function(){
			if(this.innerText == "comment"){
				debugger
				$("#comment-<%= post.id %>").html("<%= j render partial: 'comments/form' %>" )
				// this.innerText = "hide"
				// debugger
			}
		})

	})
	
// document.getElementById("co").onclick = function() {myFunction()};

// function myFunction() {
//   button = document.getElementById("co")

//   if (button.innerText == "comment"){
//   	button.innerText = "hide";
//   	$('#comment_form').show();
//   }
//   else
//   {
//   	button.innerText = "comment";
//   	$('.table2').hide();
//   	$('.comment').hide();
//   }
// }
        //validation code to see State field is mandatory.  
    
	
</script>		
	

			

app/views/posts/_sub_categories.html.erb
_sub_categories.html.erb

app/views/posts/create.js.erb
// with partial
$('#form').remove();
$('#posts').append("<%= j render partial:  @post  %>");



<%# debugger %>
 // without partial
// var node = document.querySelector('.uploader');
// $('#form').hide();
// ele = document.createElement("div");
// ele.className= "remove";
// // debugger
// ele.innerHTML = "<%= @post.title %> <%= @post.body %> <a data-remote=\"true\" href=\"/comments/new?post_id=<%= @post.id %>\">comment</a> ";
// $('.uploader').find('.empty').append(ele)
// node.insertBefore(ele,node.nextSibling);




































 // $("#post_<%= @post_last.id %>").append(newDiv.innerHTML);
// $(".posts").append('<div class="index_post"></div>')

// $("#post_<%= @post_last.id %>").append('<div class="body divya"  id= "post_<%= @post.id %>"> <%= @post.title %> <%= @post.body %> </div>');

// $('#form').remove();
// debugger
// $('.body').prepend();
// debugger
// $('#posts').prepand()
// $('#posts').prepend("<%= j render partial:  @post  %>");
// $("<%= escape_javascript(render @post) %>").insertAfter('.title');
// $('.index_new').show();
// $("<%= escape_javascript(render @post) %>").prepend("#posts");
// prepend(

app/views/posts/index.html.erb
<h1>Welcome</h1>



<%= link_to 'new post',new_post_path, remote: true%>

<div class="new"></div>

 <table id="posts" class="table1">
 	
 	<tr>
 		<th>Title</th>
 		<th>Body</th>
 		<th>Event</th>
 		<th>Count</th>
 	</tr>
 		<%= render @posts %>
 </table>

<div>
	<h1>Check box</h1>
	<%= form_tag '/posts' do%>
		<%Category.all.each do |category|%>
			<%= label_tag "#{category.name}" %>
			
			<%= check_box_tag 'category[]', "#{category.name}", false,{ class: "category_#{category.id}",id: "cat"} %><br>
			 <ul> <% category.sub_categories.each do |sub_category| %>
					<%= label_tag "#{sub_category.name}" %>
					<%= check_box_tag 'sub_category[]', "#{sub_category.name}", false, { class: "sub_category",data: {id: category.id}} %><br>
			<% end %></ul>
		<% end %>
		<%= submit_tag 'save' %>
	<% end %>
</div>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
<script type="text/javascript">
	 $(document).on("change", ".sub_category", function(){
    var id = $(this).data("id");

    if ($('.sub_category').is(':checked')){
    	$(".category_"+id).prop('checked', true);
    }
    else{
    	$(".category_"+id).prop('checked', false);
    }
  })	
</script>






<!-- <div id="posts">

	<div class="title">
		<strong>Title</strong>
		<strong>Body</strong>
		<strong>event</strong>
	</div>
	<%#= render @posts %>	
</div>
 -->

 <!-- without partial -->
<!-- <div class="index_post", id="index_<%= @posts %>">
	<%# debugger %>
	<div>
			<strong>Title</strong>
			<strong>body</strong>
			
	</div> -->
	<!-- <div class="uploader">
		<%# @posts.each do |post| %>
			<div class="test"  id= "post_<%#= post.id %>">
				<%#= post.title %>
				<%#= post.body %>
				<%#= link_to 'comment', new_comment_path(post_id: post.id), remote: true %>	
			</div>
			<div>
				<%# post.comments.each do |comment| %>
					<div class="c">
						<strong>Comment:</strong>
						<%#= comment.comment %>
					</div>
				<%# end %>
				<%# debugger %>
					<div class="comment_count" id="comment_<%#= post.id %>">
						<%# count = post.comments.count %>
						<%#= count > 0 ? count : ""  %>	
					</div>
					commentform 
				<div class="comment" id="comment-<%#= post.id %>"></div> 
				show somment
				<div class="comment_show" id="comment_show<%#= post.id %>"></div>
			</div>
		<%# end %>
			<div class="empty"></div>
	</div> -->
<!-- </div> -->
<!-- <div class="posts">
	
</div> -->
<!-- <ul id="posts">

	<div class="title">
		<strong>Title</strong>
		<strong>Body</strong>
		<strong>event</strong>
	</div>
	<%#= render @posts %>
	
	
</ul> -->

app/views/posts/new.html.erb
<h2> Create Post </h2>
<%= render 'form' %>

app/views/posts/new.js.erb
$('.new').html('<%= j render partial: "form" %>');

app/views/posts/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @post.title %>
</p>
<p>
	<strong>Body:</strong>
	<%= @post.body %>
</p>